#pragma once

#include <SDL2/SDL.h>

#define KEY_LOOK_BACKWARD SDL_SCANCODE_KP_2
#define KEY_LOOK_LEFT SDL_SCANCODE_KP_4
#define KEY_LOOK_RIGHT SDL_SCANCODE_KP_6
#define KEY_LOOK_DOWN SDL_SCANCODE_KP_8
#define KEY_LOOK_UP SDL_SCANCODE_KP_5
#define KEY_THRUST_FORWARD SDL_SCANCODE_W
#define KEY_TURN_LEFT SDL_SCANCODE_A
#define KEY_TURN_RIGHT SDL_SCANCODE_D
#define KEY_ROLL_UP SDL_SCANCODE_E
#define KEY_ROLL_DOWN SDL_SCANCODE_Q
#define KEY_STOP_THRUST SDL_SCANCODE_S
